name: Build Android APK (Professional)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  FLUTTER_VERSION: '3.19.0'
  # يمكنك تغيير اسم الحزمة والتطبيق هنا
  ORG_NAME: "com.mycompany"
  PROJECT_NAME: "my_flet_app"

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Fix and Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet
          # معالجة الخطأ الإملائي في flask تلقائياً إذا وُجد في الملف
          if [ -f requirements.txt ]; then
            sed -i 's/lask/flask/g' requirements.txt
            pip install -r requirements.txt || echo "Ignoring minor install errors..."
          fi

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Flet Build APK
        run: |
          flutter config --no-analytics
          # إضافة --yes تمنع خطأ EOFError الذي ظهر في الصور
          flet build apk --verbose --yes \
            --org ${{ env.ORG_NAME }} \
            --project ${{ env.PROJECT_NAME }} \
            --build-number ${{ github.run_number }}

      # محاولة توقيع التطبيق (ستعمل فقط إذا أضفت الأسرار في إعدادات ريبو)
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/apk
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        continue-on-error: true 

      - name: Upload Final APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flet-app-release
          # يرفع الملف الموقع إن وجد، أو الملف العادي
          path: |
            build/apk/*.apk
            ${{ steps.sign_app.outputs.signedReleaseFile }}
          if-no-files-found: error
